"""CF044: Template and docs discoverability tests for diagnostic baseline semantics.

Verifies that:
- brief.schema.json accepts diagnostic:true in mechanical criterion objects.
- Brief skeleton generated by agent_admin_brief does not contain unsafe
  human-language OR qualifiers that become unenforced hard gates.
- The acceptance-criteria guide exists and documents key baseline concepts.
- The --baseline-criteria CLI arg is discoverable via acceptance run --help.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
_SCHEMA_PATH = REPO_ROOT / "core" / "schemas" / "brief.schema.json"
_GUIDE_PATH = REPO_ROOT / "docs" / "guides" / "acceptance-criteria.md"
_BRIEF_SCRIPT = REPO_ROOT / "core" / "scripts" / "agent_admin_brief.py"
_AGENT_ADMIN = REPO_ROOT / "core" / "scripts" / "agent_admin.py"


# ---------------------------------------------------------------------------
# Schema: diagnostic field recognized
# ---------------------------------------------------------------------------

def test_schema_mechanical_item_accepts_diagnostic_field():
    """brief.schema.json must declare 'diagnostic' as a property of mechanical criterion objects."""
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    mech_items = (
        schema["properties"]["acceptance_criteria"]["properties"]["mechanical"]["items"]
    )
    obj_schema = next(
        (s for s in mech_items["anyOf"] if s.get("type") == "object"),
        None,
    )
    assert obj_schema is not None, "mechanical items must include an object variant"
    assert "diagnostic" in obj_schema.get("properties", {}), (
        "brief.schema.json must declare 'diagnostic' property in mechanical criterion objects"
    )


def test_schema_diagnostic_field_is_boolean():
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    mech_items = schema["properties"]["acceptance_criteria"]["properties"]["mechanical"]["items"]
    obj_schema = next(s for s in mech_items["anyOf"] if s.get("type") == "object")
    diag = obj_schema["properties"]["diagnostic"]
    assert diag.get("type") == "boolean", f"diagnostic must be boolean, got {diag}"


def test_schema_mechanical_description_warns_against_or_clauses():
    """The mechanical array description should warn that human OR clauses are not enforceable."""
    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    mech_desc = (
        schema["properties"]["acceptance_criteria"]["properties"]["mechanical"]
        .get("description", "")
    )
    assert "deterministic" in mech_desc.lower() or "machine" in mech_desc.lower(), (
        "mechanical description should mention deterministic/machine-deterministic requirement"
    )


# ---------------------------------------------------------------------------
# Schema: diagnostic:true accepted by jsonschema validator
# ---------------------------------------------------------------------------

@pytest.fixture
def _minimal_brief_dict():
    return {
        "task_id": "T-DIAG",
        "project": "p",
        "team": "t",
        "objective": "test diagnostic schema",
        "acceptance_criteria": {
            "mechanical": [
                {
                    "command": "true",
                    "description": "Focused gate.",
                },
                {
                    "command": "false",
                    "description": "Full-suite baseline.",
                    "diagnostic": True,
                },
            ],
            "reviewer": [],
            "operator": [],
        },
        "seats_required": ["builder"],
    }


def test_schema_accepts_diagnostic_true_when_jsonschema_available(_minimal_brief_dict):
    try:
        import jsonschema  # type: ignore
    except ImportError:
        pytest.skip("jsonschema not installed")

    schema = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
    jsonschema.validate(_minimal_brief_dict, schema)  # must not raise


# ---------------------------------------------------------------------------
# Brief skeleton: no unsafe OR wording
# ---------------------------------------------------------------------------

def _brief_skeleton_text(tmp_path: Path, monkeypatch) -> str:
    """Generate a brief skeleton and return its text."""
    monkeypatch.setenv("CLAWSEAT_REAL_HOME", str(tmp_path))
    result = subprocess.run(
        [
            sys.executable,
            str(_BRIEF_SCRIPT),
            "queue",
            "--project", "p",
            "--team", "t",
            "--task-id", "TSK-SKEL",
            "--objective", "test skeleton",
            "--no-wake",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    brief = tmp_path / ".agents" / "tasks" / "p" / "t" / "brief" / "TSK-SKEL.md"
    if not brief.exists():
        return ""
    return brief.read_text(encoding="utf-8")


# Build pattern from parts to avoid the literal string appearing in this file
# (the brief criterion 2 greps all source files for this exact text).
_UNSAFE_OR_PARTS = [
    "or " + "closeout records",
    "or record" + r"(s)? .*unrelated",
]
_UNSAFE_OR_PATTERN = re.compile("|".join(_UNSAFE_OR_PARTS), re.IGNORECASE)


def test_brief_skeleton_has_no_unsafe_or_wording(tmp_path: Path, monkeypatch):
    """Brief skeleton must not contain human OR wording that would become a hard gate."""
    text = _brief_skeleton_text(tmp_path, monkeypatch)
    matches = _UNSAFE_OR_PATTERN.findall(text)
    assert not matches, (
        f"Brief skeleton contains unsafe OR wording that becomes a hard gate: {matches}"
    )


def test_brief_skeleton_references_diagnostic_or_baseline(tmp_path: Path, monkeypatch):
    """Brief skeleton authoring comment must mention diagnostic baseline."""
    text = _brief_skeleton_text(tmp_path, monkeypatch)
    assert "diagnostic" in text.lower() or "baseline" in text.lower() or "baseline-criteria" in text.lower(), (
        "Brief skeleton should mention diagnostic/baseline to guide future authors"
    )


# ---------------------------------------------------------------------------
# Acceptance-criteria guide: exists and covers key concepts
# ---------------------------------------------------------------------------

def test_acceptance_criteria_guide_exists():
    """docs/guides/acceptance-criteria.md must exist."""
    assert _GUIDE_PATH.exists(), f"acceptance-criteria guide missing: {_GUIDE_PATH}"


def test_acceptance_criteria_guide_covers_diagnostic():
    text = _GUIDE_PATH.read_text(encoding="utf-8")
    assert "diagnostic" in text.lower(), "guide must cover diagnostic baseline"


def test_acceptance_criteria_guide_covers_baseline_criteria_flag():
    text = _GUIDE_PATH.read_text(encoding="utf-8")
    assert "--baseline-criteria" in text, "guide must document --baseline-criteria CLI arg"


def test_acceptance_criteria_guide_warns_against_or_clauses():
    text = _GUIDE_PATH.read_text(encoding="utf-8")
    has_warning = (
        "human OR" in text or
        "not enforceable" in text or
        "avoid" in text.lower() or
        "AVOID" in text or
        "WRONG" in text
    )
    assert has_warning, "guide must warn against unsafe human OR clauses"


def test_acceptance_criteria_guide_states_relevant_failures_still_block():
    text = _GUIDE_PATH.read_text(encoding="utf-8")
    assert "relevant" in text.lower() and ("block" in text.lower() or "fail" in text.lower()), (
        "guide must state that relevant failures still block acceptance"
    )


# ---------------------------------------------------------------------------
# CLI discoverability: --baseline-criteria in acceptance run --help
# ---------------------------------------------------------------------------

def test_acceptance_run_help_shows_baseline_criteria():
    """agent_admin acceptance run --help must mention --baseline-criteria."""
    result = subprocess.run(
        [sys.executable, str(_AGENT_ADMIN), "acceptance", "run", "--help"],
        capture_output=True,
        text=True,
        check=False,
    )
    output = result.stdout + result.stderr
    assert "--baseline-criteria" in output, (
        f"acceptance run --help must document --baseline-criteria; got:\n{output[:500]}"
    )


# ---------------------------------------------------------------------------
# Codebase sweep: no unsafe OR wording in templates/docs/scripts
# ---------------------------------------------------------------------------

_SEARCH_DIRS = ["core", "docs", "scripts", "tests"]


def test_no_unsafe_or_wording_in_clawseat_source():
    """None of the ClawSeat source directories may contain unsafe human OR qualifier wording.

    Regression: catches future drift where the problematic natural-language qualifier
    pattern reappears in templates, docs, or generated scripts.
    """
    found = []
    for dir_name in _SEARCH_DIRS:
        directory = REPO_ROOT / dir_name
        if not directory.is_dir():
            continue
        for path in directory.rglob("*.py"):
            if "__pycache__" in path.parts:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _UNSAFE_OR_PATTERN.search(text):
                found.append(str(path))
        for path in directory.rglob("*.md"):
            if "__pycache__" in path.parts:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if _UNSAFE_OR_PATTERN.search(text):
                found.append(str(path))
    assert not found, f"Unsafe OR wording found in: {found}"
